name: Daily LINE Push

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install flask
          python -m pip install apscheduler
          python -m pip list  # <== 這行能幫妳確認 flask 有沒有裝進去

      - name: Run push script
        run: python line_push.py
